### ISSUE TITLE
Update action workflows

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/py-template#36]
- [x] Poetry install action:
 ```yaml
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
 ```
- [x] Use cache@v2 and remove key restore
```yaml
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
```
